export const ANNIE_TYPE = 'Annie';
export const SPOTIFY_TYPE = 'Spotify';
export const DEEZER_TYPE = 'Deezer';
export const APPLE_MUSIC_TYPE = 'Apple Music';

export enum PlayStatus {
  PLAY,
  PAUSE,
  STOP,
};

export enum ContactFormReducerEnum {
  EMAIL,
  COMPLAINT,
  NAME,
  LOADING,
  FORM_SUBMITTED,
  ERROR,
};

export enum FetchStatus {
  IDLE,
  SUCCESS,
  ERROR,
  LOADING,
};

export enum ContextMenuChildName {
  COPY_LINK,
  OPEN_LINK
};

export const GA_ACTION_APP_STORE_DOWNLOAD = 'APP_STORE_DOWNLOAD';
export const GA_ACTION_PLAY_STORE_DOWNLOAD = 'PLAY_STORE_DOWNLOAD';
export const GA_ACTION_FOOTER_TWITTER_LINK = 'FOOTER_TWITTER_LINK';
export const GA_ACTION_FOOTER_INSTAGRAM_LINK = 'FOOTER_INSTAGRAM_LINK';
export const GA_ACTION_MUSIC_PLAYER = 'MUSIC_PLAYER_CLICKED';
export const GA_ACTION_SPOTIFY_LINK_COPY = 'SPOTIFY_LINK_COPY';
export const GA_ACTION_APPLE_MUSIC_LINK_COPY = 'APPLE_MUSIC_LINK_COPY';
export const GA_ACTION_DEEZER_LINK_COPY = 'DEEZER_LINK_COPY';
export const GA_ACTION_ANNIE_LINK_COPY = 'ANNIE_LINK_COPY';
export const GA_ACTION_SPOTIFY_CARD_CLICK = 'SPOTIFY_CARD_CLICK';
export const GA_ACTION_APPLE_MUSIC_CARD_CLICK =
  'APPLE_MUSIC_CARD_CLICK';
export const GA_ACTION_DEEZER_CARD_CLICK = 'DEEZER_CARD_CLICK';
export const GA_ACTION_OPEN_LINK_BUTTON_CLICK =
  'OPEN_LINK_BUTTON_CLICK';
export const GA_ACTION_LINKEDIN_LINK_SHARE = 'LINKEDIN_LINK_SHARE';
export const GA_ACTION_REDDIT_LINK_SHARE = 'REDDIT_LINK_SHARE';
export const GA_ACTION_TWITTER_LINK_SHARE = 'TWITTER_LINK_SHARE';
export const GA_ACTION_FACEBOOK_LINK_SHARE = 'FACEBOOK_LINK_SHARE';
export const GA_ACTION_WHATSAPP_LINK_SHARE = 'WHATSAPP_LINK_SHARE';
export const GA_ACTION_EMAIL_LINK_SHARE = 'EMAIL_LINK_SHARE';

export const GA_CATEGORY_DOWNLOAD_BUTTONS = 'DOWNLOAD_BUTTONS';
export const GA_CATEGORY_SOCIAL_MEDIA = 'SOCIAL_MEDIA';
export const GA_CATEGORY_TRACK_ACTIONS = 'TRACK_ACTIONS';
export const GA_CATEGORY_TRACK_SHARE_ACTIONS = 'TRACK_SHARE_ACTIONS';

export const OEMBED_BASE_URL =
  'https://api.anniemusic.app/api/v1/oembed';

export const ANNIE_USER_SELECTED_STOREFRONT_KEY =
  'ANNIE_STOREFRONT_USER_KEY';

export const ANNIE_USER_COOKIE_ACCEPT = 'ANNIE_USER_COOKIE_ACCEPT';
export const ANNIE_USER_TOKEN_KEY = 'ANNIE_USER_TOKEN';
export const ANNIE_USER_PLATFORM_TOKEN = 'ANNIE_USER_PLATFORM_TOKEN';

export const PLAYLIST_CONTEXT_ID = 'PLAYLIST_CONTEXT_ID';

export const VALID_PROVIDER_OPTIONS = ['spotify', 'deezer', 'apple_music'];

export const AUTH_NEXT_URL_KEY = 'ANNIE_AUTH_NEXT_URL';
