export const ANNIE_TYPE: string = 'Annie';
export const SPOTIFY_TYPE: string = 'Spotify';
export const DEEZER_TYPE: string = 'Deezer';
export const APPLE_MUSIC_TYPE: string = 'Apple Music';

export enum PlayStatus {
  PLAY,
  PAUSE,
  STOP
}

export enum ContactFormReducerEnum {
  EMAIL,
  COMPLAINT
}

export const GA_ACTION_APP_STORE_DOWNLOAD = 'APP_STORE_DOWNLOAD';
export const GA_ACTION_PLAY_STORE_DOWNLOAD = 'PLAY_STORE_DOWNLOAD';
export const GA_ACTION_FOOTER_TWITTER_LINK = 'FOOTER_TWITTER_LINK';
export const GA_ACTION_FOOTER_INSTAGRAM_LINK = 'FOOTER_INSTAGRAM_LINK';
export const GA_ACTION_MUSIC_PLAYER = 'MUSIC_PLAYER_CLICKED';
export const GA_ACTION_SPOTIFY_LINK_COPY = 'SPOTIFY_LINK_COPY';
export const GA_ACTION_APPLE_MUSIC_LINK_COPY = 'APPLE_MUSIC_LINK_COPY';
export const GA_ACTION_DEEZER_LINK_COPY = 'DEEZER_LINK_COPY';
export const GA_ACTION_ANNIE_LINK_COPY = 'ANNIE_LINK_COPY';
export const GA_ACTION_SPOTIFY_CARD_CLICK = 'SPOTIFY_CARD_CLICK';
export const GA_ACTION_APPLE_MUSIC_CARD_CLICK = 'APPLE_MUSIC_CARD_CLICK';
export const GA_ACTION_DEEZER_CARD_CLICK = 'DEEZER_CARD_CLICK';
export const GA_ACTION_OPEN_LINK_BUTTON_CLICK = 'OPEN_LINK_BUTTON_CLICK';

export const GA_CATEGORY_DOWNLOAD_BUTTONS = 'DOWNLOAD_BUTTONS';
export const GA_CATEGORY_SOCIAL_MEDIA = 'SOCIAL_MEDIA';
export const GA_CATEGORY_TRACK_ACTIONS = 'TRACK ACTIONS';

export const OEMBED_BASE_URL = 'https://api.anniemusic.app/api/v1/oembed'
