name: Annie Web CI

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: 'test'
      ANNIE_API_BASE_URL: 'localhost:5000/api'
      ANNIE_CLIENT_BASE_URL: 'localhost:3000'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: annie-ci-cache
        with:
          path: ./*
          key: ${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-annie-

      - name: Run Linter for Annie-Web
        run: yarn lint

  test:
    runs-on: ubuntu-latest

    needs: lint

    env:
      NODE_ENV: 'test'
      ANNIE_API_BASE_URL: 'localhost:5000/api'
      ANNIE_CLIENT_BASE_URL: 'localhost:3000'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: annie-ci-cache
        with:
          path: ./*
          key: ${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-annie-

      - name: Run test for Annie Web
        run: yarn test

  deployToStaging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Notify slack stage build
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C01HMJ656KV
          status: STARTING
          color: warning

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C01HMJ656KV
          status: FAILED
          color: danger

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C01HMJ656KV
          status: SUCCESS
          color: good
